[October 31, 2019, 21:11:45.000 UTC] Caught exception in method AmazonAI_Cloudformation::check_acm_cert_creation in class AmazonAI_Cloudformation: 
Stack is in an unexpected state. Certificate state is: PENDING_VALIDATION and Stack state is: CREATE_FAILED
[October 31, 2019, 21:11:50.000 UTC] Caught exception in method AmazonAI_Cloudformation::check_stack_deletion in class AmazonAI_Cloudformation: 
The stack is an unexpected state. The three latest stack events are:<br><br>
                1. <b>Resource Type</b>: AWS::CertificateManager::Certificate 
                 <b>Resource Status</b>: CREATE_FAILED 
                 <b>Status Reason</b>: Resource creation cancelled<br>
                2. <b>Resource Type</b>: AWS::CloudFormation::Stack 
                 <b>Resource Status</b>: DELETE_IN_PROGRESS 
                 <b>Status Reason</b>: User Initiated<br>
                3. <b>Resource Type</b>: AWS::CertificateManager::Certificate 
                 <b>Resource Status</b>: CREATE_IN_PROGRESS
                 <b>Status Reason</b>: Resource creation Initiated<br>
[October 31, 2019, 21:11:53.000 UTC] Caught exception in method AmazonAI_Cloudformation::check_stack_deletion in class AmazonAI_Cloudformation: 
The stack is an unexpected state. The three latest stack events are:<br><br>
                1. <b>Resource Type</b>: AWS::CertificateManager::Certificate 
                 <b>Resource Status</b>: CREATE_FAILED 
                 <b>Status Reason</b>: Resource creation cancelled<br>
                2. <b>Resource Type</b>: AWS::CloudFormation::Stack 
                 <b>Resource Status</b>: DELETE_IN_PROGRESS 
                 <b>Status Reason</b>: User Initiated<br>
                3. <b>Resource Type</b>: AWS::CertificateManager::Certificate 
                 <b>Resource Status</b>: CREATE_IN_PROGRESS
                 <b>Status Reason</b>: Resource creation Initiated<br>
